using System;

namespace WebSockets.Core
{
    /// <summary>
    /// The interface for a nonce generator.
    /// </summary>
    public interface INonceGenerator
    {
        /// <summary>
        /// Create a mask for a websocket message.
        /// 
        /// A mask is a four byte array containing random data.
        /// 
        /// The mask is not intended to ensure security, but to
        /// prevent network infrastructure misinterpreting data.
        /// </summary>
        /// <returns>The mask.</returns>
        byte[] CreateMask();

        /// <summary>
        /// Creates a random key for use in a handshake.
        /// 
        /// The key is a sixteen byte array of randomly generated bytes,
        /// converted to a base 64 encoded string.
        /// </summary>
        /// <returns>The generated key.</returns>
        string CreateClientKey();
    }

    /// <summary>
    /// A nonce generator.
    /// </summary>
    public class NonceGenerator : INonceGenerator
    {
        public static readonly Random _random;

        /// <summary>
        /// Initialize a random number generator.
        /// </summary>
        static NonceGenerator()
        {
            _random = new Random((int)DateTime.Now.Ticks);
        }

        /// <inheritdoc />
        public byte[] CreateMask()
        {
            var nonce = new byte[4];
            _random.NextBytes(nonce);
            return nonce;
        }

        /// <inheritdoc />
        public string CreateClientKey()
        {
            var nonce = new byte[16];
            _random.NextBytes(nonce);
            return Convert.ToBase64String(nonce);
        }
    }
}